### ISSUE TITLE
Endpoint not created correctly

### ISSUE THREAD

**Issue by thomas-vt** [curuvija/charts#2]
Installed chart but the service endpoint is not populated correctly. 
Prometheus cannot automatically do the service discovery due to this issue

eg:

> $ kubectl -n \<namespace\> get endpoints oracledb-exporter
> NAME                ENDPOINTS   AGE
> oracledb-exporter   \<none\>      5m19s

**Comment by thomas-vt** [comment]
Although the service show the endpoint IP address but the endpoint itself shows \<none\>

> $ kubectl -n \<namespace\> describe service oracledb-exporter
Name:                     oracledb-exporter
Namespace:                monitoring
Labels:                   app=oracledb-exporter
                          app.kubernetes.io/instance=oracledb-exporter
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=oracledb-exporter
                          app.kubernetes.io/version=0.6.0
                          helm.sh/chart=oracledb-exporter-1.0.0
                          release=oracledb-exporter
Annotations:              meta.helm.sh/release-name: oracledb-exporter
                          meta.helm.sh/release-namespace: infra
Selector:                 app.kubernetes.io/instance=oracledb-exporter,app.kubernetes.io/name=oracledb-exporter,app=oracledb-exporter,release=oracledb-exporter
Type:                     ClusterIP
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       x.y.z.z
IPs:                       x.y.z.z
Port:                     http  9161/TCP
TargetPort:               http/TCP
Endpoints:                10.11.12.13 <--
Session Affinity:         None
Internal Traffic Policy:  Cluster
Events:                   <none>

**Comment by thomas-vt** [comment]
Got it working by changing file oracledb-exporter/templates/service.yaml line

      targetPort: {{ .Values.service.port }}

**Comment by curuvija** [comment]
hi @thomas-vt sorry for the inconvenience and late reply. Thanks for finding this issue. I'm quite busy these days. I'll try to find some time to fix it. I didn't expect anyone to use it, this is my helm chart playground environment for learning with a very low priority.
